### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by snowyivu** [ethteck/pokemonsnap#1]
Hey there! Not sure if this is necessary for linux machines, but I found that after installing MinGW and making a copy of python.exe named python3.exe on Windows, I did have to grab these python packages before I was able to run the "make setup" command:

pip install python-ranges
pip install pyyaml
pip install capstone

Might be useful to add to the readme instructions :)

Also - I'm curious if you have any specific goals with this project? I managed to find it because I'm interested in working on what I (naively) believe to be a pretty small game mod for Pokemon Snap. If you're at all interested in answering some beginner questions, gaining an apprentice, or even collaborating, please do reach out to me (Email: snowyivu@gmail.com Discord: Batsu#0166 or even Twitter: @Maebatsu )

**Comment by ethteck** [comment]
Thanks for this! I added a requirements.txt and note in the README.md. I added you on Discord - happy to talk more there!
